defaults: &defaults
  environment:
    TZ: "/usr/share/zoneinfo/Asia/Tokyo"

deploy: &deploy
  <<: *defaults
  machine:
    enabled: true
  steps:
  - checkout
  - run:
      name: Setup Heroku
      command: bash .circleci/setup-heroku.sh
  - run:
      name: push
      command: |
        pwd
        ls
        heroku login
        git config --global user.email "tatsuya.0803s@gmail.com"
        git config --global user.name "ttatsato"
        git remote add heroku https://git.heroku.com/alby-co-jp.git
        git remote -v
        git add .
        git commit -m "deploy"
        git push -f heroku master

  container_config: &container_config
    docker:
    - image: circleci/node

version: 2
jobs:
  build:
    docker:
    - image: docker:17.05.0-ce-git
    steps:
    - checkout
    - setup_remote_docker
    - run:
        name: Install dependencies
        command: |
          apk add --no-cache \
            py-pip=9.0.0-r1 bash
          apk update && apk upgrade && apk add curl
          pip install \
            awscli==1.11.76

  npm_install:
    <<: *container_config
    steps:
    - checkout

    - restore_cache:
        keys:
        - node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
        - node-v1-{{ .Branch }}-
        - node-v1-

    - run:
        name: install-npm
        command: yarn global add npm
    - run:
        name: update-npm
        command: npm install npm
    - run:
        name: install-npm-dependencies
        command: npm install
    - save_cache:
        paths:
        - ~/usr/local/lib/node_modules
        key: node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}

  deploy_to_heroku:
    <<: *deploy
    environment:
      HEROKU_APP_NAME: "Appname" #　本番のapp_nameを設定

  deploy_to_heroku_stg:
    <<: *deploy
    environment:
      HEROKU_APP_NAME: "workup-web" #stg環境ののapp_nameを設定

workflows:
  version: 2
  build:
    jobs:
    # - npm_install:
    #     filters:
    #       branches:
    #         only:
    #           - /^feature\/.*/
    #           - develop
    - deploy_to_heroku_stg:
        filters:
          branches:
            only:
            - /^feature\/.*/
            - develop
        # requires:
        #       - npm_install